
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://121.41.178.85:28848
      config:
        server-addr: http://121.41.178.85:28848
  config:
    import: nacos:pay.yaml

server:
  port: 29001


